// Additional Constraints
export const qualityChecks = [
  { id: "no-extent",
    title: "Missing extent",
    description: "Records without an extent or size.",
    jsonpointer: "/extent", fails: item => !item.extent },
  { id: "no-license",
    title: "Missing license",
    description: "Records without a license.",
    jsonpointer: "/license", fails: item => !item.license },
  { id: "no-abstract", description: "Records without an abstract.",
    title: "Missing abstract", jsonpointer: "/definition", fails: item => !item.definition },
  { id: "no-homepage",
    description: "Records without a website URL.",
    title: "Missing homepage", jsonpointer: "/url", fails: item => !item.url },
  { id: "no-publisher",
    description: "Records without a publisher.",
    title: "Missing publisher", jsonpointer: "/publisher", fails: item => !item.publisher },
  { id: "no-subject",
    description: "Records without a subject classification.",
    title: "Missing subject", jsonpointer: "/subject", fails: item => !item.subject },
  { id: "no-kos-type",
    description: "Records without a specific knowledge organization system type.",
    title: "Missing KOS type", jsonpointer: "/type", fails: item => (item.type?.length ?? 0) < 2 },
  { id: "no-format",
    title: "Missing format", jsonpointer: "/FORMAT", fails: item => !item.FORMAT },
  { id: "no-languages",
    description: "Records without listed content languages.",
    title: "Missing languages", jsonpointer: "/languages", fails: item => !item.languages },
  { id: "api-but-no-examples",
    description: "API endpoints with no notation examples.",
    title: "API provided without notation examples", jsonpointer: "/notationExamples", fails: item => Boolean(item.API) && !item.notationExamples },
]
